#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

FILE="$1"
BNFILE=$(basename $FILE)
SFILE=${BNFILE%.txt}
DESTDIR="$(dirname $FILE)/${SFILE}"

CLEANTXT="$DESTDIR/$SFILE.clean.txt"
FREQFILE="$DESTDIR/$SFILE.freq"
WCFILE="$DESTDIR/$SFILE.wordcount"

if [ -e "$FILE" ]; then
  echo "filename=$BNFILE"
else
  echo "File does not exist: $1" >&2
  exit -1
fi

echo "Creating dest dir $DESTDIR..." >&2
mkdir -p "$DESTDIR"

if [ -f "$CLEANTXT" ]; then
  echo "Cleaned text exists; skipping." >&2
else
  echo "Cleaning text..." >&2
  $DIR/remix/cleantext "$1" -o $CLEANTXT
fi

if [ -f "$WCFILE" ]; then
  echo "Wordcount file exists; skipping." >&2
else
  echo "Counting words..." >&2
  $DIR/wordcount $CLEANTXT $WCFILE
fi

if [ -f "$FREQFILE" ]; then
  echo "Frequency counts file exists; skipping." >&2
else
  echo "Creating 1-5grams..." >&2
  $DIR/ngram $CLEANTXT $FREQFILE
fi

if [ -f "$FREQFILE.5grams" ]; then
  echo "Ngrams frequency files exist; skipping." >&2
else
  echo "Splitting ngrams into files..." >&2
  $DIR/splitdashes $FREQFILE
fi

WORDCOUNT=$(cat $WCFILE)
echo "wordcount=${WORDCOUNT:-0}"

echo "Creating triples..." >&2
for N in 1 2 3 4 5; do
  echo "${N}grams..." >&2
  for SUBSET in int-bom int-bom.no-kjv; do
    echo "$SUBSET" >&2

    if [[ "$SUBSET" == "int-bom" ]]; then DBSUBSET=""; fi
    if [[ "$SUBSET" == "int-bom.no-kjv" ]]; then DBSUBSET="nokjv_"; fi

    BOMFILE=$DIR/bom2/bom-1830.freq.${N}grams.${SUBSET}.weight+freq
    TRIPLEFILE=${FREQFILE}.${N}grams.${SUBSET}.triple
    if [ -f "$TRIPLEFILE" ]; then
      echo "Triple file exists; skipping." >&2
    else
      join -1 1 -2 1 $BOMFILE ${FREQFILE}.${N}grams >$TRIPLEFILE
    fi

    SCORE=$($DIR/score $TRIPLEFILE | awk '{ print $1 }')
    echo "score_bom_${DBSUBSET}${N}g=${SCORE:-0}"

#    for SECTION in 1ne 2ne 3ne 4ne alm eno eth hel jac jar mni mor mos omn pre wom; do
#      BOMFILE=$DIR/bom2/bom-1830.${SECTION}.freq.${N}grams.${SUBSET}.weight+freq
#      TRIPLEFILE=${FREQFILE}.${N}grams.${SECTION}.${SUBSET}.triple
#      join -1 1 -2 1 $BOMFILE ${FREQFILE}.${N}grams >$TRIPLEFILE
#      SCORE=$($DIR/score $TRIPLEFILE | awk '{ print $1 }')
  
#      echo "score_${SECTION}_${DBSUBSET}${N}g=${SCORE:-0}"
#    done
  done
done

