#!/usr/bin/env ruby
require_relative "pgconn"

DIR = File.dirname(__FILE__)

$conn.prepare("insert_book", 
  "INSERT INTO books (archive_org_id, title, year, author) " + 
  "VALUES ($1, $2, $3, $4) RETURNING id")
$conn.prepare("bulk_copy",
  "COPY $1 FROM STDIN")
$conn.prepare("insert_freqs", <<-SQL
  INSERT INTO frequencies (book_id, ngram_id, freq)
  SELECT $1, g.id, freq
  FROM tmp_ngrams_freq t
  JOIN arrgrams g ON g.n = array_length(t.gram, 1) AND g.gram = t.gram;
SQL

def copy_data(table, file)
  $conn.exec_prepared("bulk_copy", table)
  begin
    while file.read( 4096, buf )
      until conn.put_copy_data( buf )
        sleep 0.1
      end
    end
  rescue Errno => err
    errmsg = "%s while reading copy data: %s" % [ err.class.name, err.message ]
    conn.put_copy_end( errmsg )
  else
    conn.put_copy_end
    while res = conn.get_result
      $stderr.puts "Result of COPY is: %s" % [ res.res_status(res.result_status) ]
    end
  end
end

def import_frequency_file(book_id, filepath)
  File.open(filepath) do |file|
    conn.transaction do
      $conn.exec( <<-SQL )
        CREATE TEMP TABLE tmp_ngrams_freq (
          gram TEXT[],
          freq INTEGER NOT NULL DEFAULT 1
        ) ON COMMIT DROP;
      SQL
      bulk_copy("tmp_ngrams_freq", file)
      $conn.exec( <<-SQL )
        INSERT INTO arrgrams (n, gram)
        SELECT array_length(gram, 1), gram FROM tmp_ngrams_freq;
      SQL
      $conn.exec_prepared("insert_freqs", book_id)
    end
  end
end

def create_book(archive_org_id, title, year, author)
  $conn.exec_prepared("ins", [archive_org_id, title, year, author]).first["id"]
end

$stdin.each_line do |line|
  archive_org_id, title, year, author = line.chomp.split("\t")
  book_id = create_book(archive_org_id, title, year, author)

end


$stdin.each_line do |line|
  archive_org_id, book_id = line.chomp.split("\t")
  txt_filepath = File.join(DIR, "library", archive_org_id + ".txt")

  book_id = `#{File.join(DIR, "create_book")}`
  `cat #{freq_filepath} | sed 's/-/,/g' | awk '{print "{" $1 "}" FS $2}' | psql -f $(#{File.join(DIR, "import_freq")} #{book_id}) test

end

