#!/bin/bash

gunzip -c ol_cdump_latest.txt.gz \
| pv -cN raw \
| grep '^/type/edition' \
| pv -cN editions \
| awk -F $'\t' '{ print $5 }' \
| json -c 'this.languages == null || (this.languages.length > 0 && (this.languages[0].key == "/languages/eng" || this.languages[0].key == "/languages/und"))' \
       -c 'this.publish_date < 1830' \
       -d $'\t' -g -a key publish_date title authors.0.key \
| pv -cN found \
> archive.catalog.pre1830.txt
