#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CLEANTXT="${1%.txt}.clean.txt"
FREQFILE="${1%.txt}.freq"
WCFILE="${1%.txt}.wordcount"

echo "BoM text: $1"
echo "Cleaning BoM text..."
$DIR/remix/cleantext "$1" -o $CLEANTXT
echo "Counting words..."
$DIR/wordcount $CLEANTXT $WCFILE
echo "Creating 1-5grams..."
$DIR/ngram $CLEANTXT $FREQFILE
echo "Splitting ngrams into files..."
$DIR/splitdashes $FREQFILE

echo "Creating ngram indices..."
for N in 1 2 3 4 5; do
  echo "${N}grams..."
  cat ${FREQFILE}.${N}grams | awk '{ print $1 }' >${1%.txt}.index.${N}grams
done

echo "Adding weight column..."
for N in 1 2 3 4 5; do
  echo "${N}grams..."
  cat $DIR/${N}grams.int-bom.freq | join -1 1 -2 1 - ${FREQFILE}.${N}grams >${FREQFILE}.${N}grams.int-bom.weight+freq
  cat $DIR/${N}grams.int-kjv.freq | join -1 1 -2 1 - ${FREQFILE}.${N}grams >${FREQFILE}.${N}grams.int-kjv.weight+freq
  cat $DIR/${N}grams.int-bom.no-kjv.freq | join -1 1 -2 1 - ${FREQFILE}.${N}grams >${FREQFILE}.${N}grams.int-bom.no-kjv.weight+freq
done

echo "Removing temp files..."
rm -f $CLEANTXT
rm -f $FREQFILE
