#!/usr/bin/env ruby
require 'optparse'
require_relative 'remix'

options = {:output => $stdout, :remove_bib => true}
OptionParser.new do |opts|
  opts.banner = "Usage: cleantext [options] [FILES]"

  opts.on("-o", "--output FILENAME", "Send output to filename") do |filename|
    options[:output] = File.open(filename, "w")
  end
  opts.on("-r", "--[no-]remove-biblical-headings", "Remove headings such as Isa2:15") do |yes|
    options[:remove_bib] = yes
  end
end.parse!

if ARGV.size > 0
# Use files as input
  ARGV.each do |filename|
    File.open(filename) do |file|
      Remix.clean_text(file, options[:output], options[:remove_bib])
    end
  end
else
# Use stdin as input
  $stdin.set_encoding "UTF-8"
  Remix.clean_text($stdin, options[:output], options[:remove_bib])
end
